name: "Issue and PR Labeler"

on:
  pull_request:
    types: [opened, synchronized, edited]
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
